name: Python CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t simple-python-app .

      - name: Run tests in Docker
        run: |
          docker run --rm simple-python-app

      - name: Deploy to test environment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to test environment..."
          docker run --rm simple-python-app
          echo "Deployment successful!"
